version: '3.7'

services:
  db:
    image: postgres
    container_name: apivendas-db
    restart: 'no'
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apivendas
